Workaround for XCode failing to find tolua++ generated files (including generated/toluabind.c, which was used to build tolua++).
For example, this error:
> error: Build input file cannot be found: '/Users/runner/work/U3D/U3D/build/ci/Source/ThirdParty/toluapp/src/bin/generated/toluabind.c'.
> Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'tolua++' from project 'Urho3D')