Fixed usage of deprecated GLSL function texture2DLod. It is now textureLod. Error message was: (0(857) : error C7616: global function texture2DLod is removed after version 140)